version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root1234  # 여기에 비밀번호를 지정
      MYSQL_DATABASE: todo
    ports:
      - "3306:3306"
    networks:
      - default

  app:
    build: .
    container_name: spring-container
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/todo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234