spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo
    username: root
    password: root1234

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html